### ISSUE TITLE
non-deterministic failures in the test suite in v0.2.3

### ISSUE THREAD

**Issue by decathorpe** [smol-rs/piper#18]
I'm responsible for maintaining the Fedora Linux package for this crate. I infrequently get errors from our CI pipeline about failed builds due to issues in the test suite, but the failures don't seem to be deterministic, and I've seen them happen on different CPU architectures.

I now managed to get logs for two different failures that happened on x86_64 and aarch64-unknown-linux-gnu (on Rust 1.79 / 1.80 with `--release`, in possibly heavily multi-threaded environments):

on aarch64-unknown-linux-gnu:

```
---- src/lib.rs - Reader::is_empty (line 408) stdout ----
Test executable failed (exit status: 101).
stderr:
thread 'main' panicked at src/lib.rs:10:1:
assertion failed: !reader.is_empty()
```

on x86_64-unknown-linux-gnu:

```
---- src/lib.rs - Writer::is_full (line 764) stdout ----
Test executable failed (exit status: 101).
stderr:
thread 'main' panicked at src/lib.rs:10:1:
assertion failed: writer.is_full()
```

This looks like there's a race condition somewhere that's hit in rare circumstances (but not too rare, since it keeps making our CI turn red occasionally).

**Comment by notgull** [comment]
Thanks for reporting this! Give me some time to reproduce

**Comment by notgull** [comment]
I've reproduced this issue. It appears to happen when the random yield happens during `poll_fill_bytes`. Standby for a fix.

**Comment by decathorpe** [comment]
Awesome, thank you!
